# Generated by Django 3.0.7 on 2020-06-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200604_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librodiario',
            name='debe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='librodiario',
            name='haber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
