# Generated by Django 3.0.7 on 2020-06-05 06:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200605_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libromayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('saldo_deudor', models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('saldo_acreedor', models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('numero_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Catalogocuenta')),
            ],
        ),
        migrations.DeleteModel(
            name='Periodo',
        ),
    ]
