# Generated by Django 3.0.7 on 2020-06-05 13:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200605_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libromayor',
            name='saldo_acreedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='saldo_deudor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='saldo_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
